// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(HobbyContext))]
    [Migration("20220422000543_SaraHobby")]
    partial class SaraHobby
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyId"), 1L, 1);

                    b.Property<string>("HobbyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbys");

                    b.HasData(
                        new
                        {
                            HobbyId = 1,
                            HobbyDescription = "Cooking for my family makes me happy",
                            HobbyName = "Cooking"
                        },
                        new
                        {
                            HobbyId = 2,
                            HobbyDescription = "Swimming in water makes me feel relax",
                            HobbyName = "Swimming"
                        },
                        new
                        {
                            HobbyId = 3,
                            HobbyDescription = "Playing with my friends",
                            HobbyName = "Video Games"
                        },
                        new
                        {
                            HobbyId = 4,
                            HobbyDescription = "Creating in my art journal allows me to express myself",
                            HobbyName = "Art Journal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
